/**
 * All action types should be listed here
 */
module.exports = {
  // createTodoList
  CREATE_TODO_LIST_PENDING: 'CREATE_TODO_LIST_PENDING',
  CREATE_TODO_LIST_SUCCESS: 'CREATE_TODO_LIST_SUCCESS',
  CREATE_TODO_LIST_FAILURE: 'CREATE_TODO_LIST_FAILURE',
  // deleteTodoList
  DELETE_TODO_LIST_PENDING: 'DELETE_TODO_LIST_PENDING',
  DELETE_TODO_LIST_SUCCESS: 'DELETE_TODO_LIST_SUCCESS',
  DELETE_TODO_LIST_FAILURE: 'DELETE_TODO_LIST_FAILURE',
  // selectTodoList
  SELECT_TODO_LIST: 'SELECT_TODO_LIST',

  // addTodo
  ADD_TODO_PENDING: 'ADD_TODO_PENDING',
  ADD_TODO_SUCCESS: 'ADD_TODO_SUCCESS',
  ADD_TODO_FAILURE: 'ADD_TODO_FAILURE',
  // toggleTodo
  TOGGLE_TODO_PENDING: 'TOGGLE_TODO_PENDING',
  TOGGLE_TODO_SUCCESS: 'TOGGLE_TODO_SUCCESS',
  TOGGLE_TODO_FAILURE: 'TOGGLE_TODO_FAILURE',
  // markAllComplete
  MARK_ALL_COMPLETE_PENDING: 'MARK_ALL_COMPLETE_PENDING',
  MARK_ALL_COMPLETE_SUCCESS: 'MARK_ALL_COMPLETE_SUCCESS',
  MARK_ALL_COMPLETE_FAILURE: 'MARK_ALL_COMPLETE_FAILURE',
};
