/**
 * All action types should be listed here
 */
module.exports = {
  // createTodoList
  CREATE_TODO_LIST_PENDING: 'CREATE_TODO_LIST_PENDING',
  CREATE_TODO_LIST_SUCCESS: 'CREATE_TODO_LIST_SUCCESS',
  CREATE_TODO_LIST_FAILURE: 'CREATE_TODO_LIST_FAILURE',

  // addTodo
  ADD_TODO_PENDING: 'ADD_TODO_PENDING',
  ADD_TODO_SUCCESS: 'ADD_TODO_SUCCESS',
  ADD_TODO_FAILURE: 'ADD_TODO_FAILURE',
};
